/** Generated by scripts/create-stripe-products.mjs — re-run script to refresh IDs */
import type { AdCountOption } from './1800-ads-pricing'

export const STRIPE_PRICE_IDS: Record<AdCountOption, string> = {
  5: 'price_1Tvl1QCxHonHSapKn11RS99F',
  10: 'price_1Tvl8oCxHonHSapKkHfM5Y9Q',
  20: 'price_1Tvl8oCxHonHSapKUNQVYH30',
  50: 'price_1Tvl8pCxHonHSapKrgZQspv1',
  100: 'price_1Tvl8pCxHonHSapK49AzKrrb',
}

export const STRIPE_PRODUCT_IDS: Record<AdCountOption, string> = {
  5: 'prod_Ur9A658hl5ZS0U',
  10: 'prod_Ur9AaBgow4Ocaj',
  20: 'prod_Ur9ALHQX0tWx8E',
  50: 'prod_Ur9A340z4Q0w2g',
  100: 'prod_Ur9AA5YBCRynO2',
}
